### ISSUE TITLE
How to setup database

### ISSUE THREAD

**Issue by pradeephyd** [smq100/inish-optionanalysis#1]
any instructions to set up database.

**Comment by smq100** [comment]
The code uses a standard implementation of SQLAlchemy to abstract the database layer. Many online resources available for that tool. The database code is in the ‘data’ directory (including the __init__.py file). models.py contains the table schema. store.py the access methods for the financial data. manager.py for managing the database. I’ve used both Postgres and SQLite, but I recommend Postgres because it behaves better with my multi-threaded data fetching.

The console_manager.py file contains good examples of how to use the database functionality.

Thanks,
Steve

Just a reminder that this is a personal project and so the project is not documented as thoroughly as more public projects are.



From: pradeephyd ***@***.***>
Date: Tuesday, June 8, 2021 at 1:05 PM
To: smq100/inish-optionanalysis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smq100/inish-optionanalysis] How to setup database (#1)

any instructions to set up database.

**Comment by pradeephyd** [comment]
Thank you so much for the quick reply :). will try it.

**Comment by pradeephyd** [comment]
actually, the database files and ini,xlsx files are missing in the data folder

**Comment by smq100** [comment]
I added sample xlsx files to the data/symbols directory. The ini file contains database login info so it is not included.

**Comment by pradeephyd** [comment]
tried updating code to create tables if db is not found (securities.db), but seems more dependency was there, and the application is crashing. updated code create ini file with default values if it does not exist, will request push once i fixed DB issue

**Comment by smq100** [comment]
securities.db is the SQLite database file. The ini file is only used with Postgres. You specify the db in data/__init__.py by specifying the ACTIVE_DB = OPTIONS_DB[0]. 0 = Postgres, 1 = SQLite. 

The securities.db file is created when resetting the SQLite database. See console_manager.py/reset_database() for the steps to reset the database. I confirmed that it works.

**Comment by pradeephyd** [comment]
Finally worked, changed default "Googe" to 'excel'. If possible can you give a brief explanation of how to select/buy stocks and options. Nice view support and resistance screen, but a little bit of confusion in reading the chart, maybe if we use candlesticks it will look good. Anyway, really great effort :) Thank you.

**Comment by smq100** [comment]
This code does not support buying anything. It is meant to support analyses prior to any buying or shorting. 

I have found that candlesticks on the support/resistance chart adds more confusion. Only the highs & lows are relevant to determine the pivot points and subsequent lines.

**Comment by pradeephyd** [comment]
Ok thank you.
